### ISSUE TITLE
escaping url's

### ISSUE THREAD

**Issue by WebNinjrDesign** [toddmotto/html5blank#103]
Should you be escaping urls..
```
<link href="<?php echo esc_url (get_template_directory_uri()); ?>/img/icons/touch.png" rel="apple-touch-icon-precomposed">
```

Reference: https://codex.wordpress.org/Function_Reference/esc_url

**Comment by oriSomething** [comment]
it's very minor issues if at all (at least for the `get_template_directory_uri `), but would you make a PR?
