### ISSUE TITLE
website unreachable

### ISSUE THREAD

**Issue by htrex** [toddmotto/html5blank#116]
http://html5blank.com/ is unreachable from several days.
What's going on? Is this project abandoned?

**Comment by toddmotto** [comment]
Hmm, very strange! I'm seeing it perfectly, where abouts are you in the world?

<img width="880" alt="screen shot 2015-10-07 at 16 18 58" src="https://cloud.githubusercontent.com/assets/1655968/10342036/25b6ee04-6d0f-11e5-8315-3c323a5d2e4d.png">

**Comment by grischka** [comment]
Fine here as well... And here: http://downforeveryoneorjustme.com/html5blank.com

**Comment by htrex** [comment]
now is back online for me too.
when I've opened this issue the result from http://downforeveryoneorjustme.com/html5blank.com was down for everyone.
