### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by michaelHeimes** [toddmotto/html5blank#124]
So far Woocommerce has worked fine after some CSS tweaks. With 2.5, I've had at least one plugin not work and I don't know if it's a plugin issue or a compatibility issue with this theme.

**Comment by oriSomething** [comment]
there is too much missing information. if you won't bring enough details i'll have to close this issue

**Comment by michaelHeimes** [comment]
Sorry. A plugin I recently purchased called Extra Product Options no longer works after the Woocommerce 2.5 and 2.5.1 updates. I didn't know if this was an issue with the theme after Woocommerce changed core files.

**Comment by conorcussell** [comment]
@michaelHeimes This is an issue to raise with the plugin developers - http://codecanyon.net/user/themecomplete

**Comment by oriSomething** [comment]
okay, can you confirm the issue related to `html5 blank`?
if yes - please give a relevant information so it could be handled
if no - please close the issue

**Comment by michaelHeimes** [comment]
I figured out the issue and it had nothing to do with HTML5 Blank. Thank you for your responses.
