### ISSUE TITLE
ERROR: This feed is ivalid (after update WP 4.7)

### ISSUE THREAD

**Issue by alfredo49** [toddmotto/html5blank#160]
My feeds works perfect in wp previous versions, but since i updated “ERROR: THIS FEED IS INVALID” in a blank screen

Help please! 🙁

**Comment by oriSomething** [comment]
was it in a fresh installation of **HTML5 Blank**? Since, I have a few website that upgraded to WP 4.7 and still work

**Comment by alfredo49** [comment]
Is a wp4.7 bug with custom post types feeds that returns an error, it thinks that the feed is empty. It will be fixed in wp4.7.1, my fault , there wasnt a theme bug :-)
