### ISSUE TITLE
Problem installing at the "npm run modernizr" point

### ISSUE THREAD

**Issue by GuiHarrison** [toddmotto/html5blank#174]
Hi all! I'm having a bit of a problem installing the latest theme with the run modernizr step. I've updated all dependencies (node.js, npm, bower) and still am having the following problem:

`npm run modernizr`

> 
> > HTML5Blank@1.5.0 modernizr D:\Program Files (x86)\Ampps\www\profiv\wp-content\themes\html5blank
> > cd node_modules/modernizr && ./bin/modernizr -c lib/config-all.json && mv ./modernizr.js ../../src/js/lib/modernizr.js
> 
> '.' is not recognized as an internal or external command,
>      operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! HTML5Blank@1.5.0 modernizr: `cd node_modules/modernizr && ./bin/modernizr -c lib/config-all.json && mv ./modernizr.js ../../src/js/lib/modernizr.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the HTML5Blank@1.5.0 modernizr script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     D:\Users\me\AppData\Roaming\npm-cache\_logs\2017-10-19T04_41_46_155Z-debug.log
> 

You guys have gone through this problem?

**Comment by lregla** [comment]
Have you ruled out the possibility that gulp is not installed globally?

**Comment by pgerochi** [comment]
This is true, and I’m currently working on the web pack task. I unfortunately don’t have a windows machine so I’m unable to check.

**Comment by lregla** [comment]
I added a PR #175 that replaces the npm build of modernizr with gulp. This removes the dependency for the bash command line and makes things more compatible OS-wise.

**Comment by lregla** [comment]
@GuiHarrison Now that #175 has been merged you should pull from master and confirm whether this fixes the issue on your local machine.

**Comment by GuiHarrison** [comment]
Hi! that was exactly the problem. I later tested on bash and it worked and, on the windows machine, ran the copying manually changing ./bin/modernizr to bin\modernizr and it worked as well. With the new merge everything seems to be working just fine!
