### ISSUE TITLE
gulp workflow

### ISSUE THREAD

**Issue by isaacalves** [toddmotto/html5blank#98]
I'd like to use a Gulp workflow with html5blank, mainly for using BrowserSync, compiling Sass (using autoprefixer and sourcemaps), and managing (and wiring) Bower dependencies.

Anyone has any thoughts on that or have tried something similar?

I'm currently working on that, starting from [gulp-webapp](https://github.com/yeoman/generator-gulp-webapp)'s Gulp implementation.

**Comment by oriSomething** [comment]
this project use gulp and has gulp tasks. i don't understand what you seek for

**Comment by joshhowenstine** [comment]
Are you asking about using BrowserSync in place of LiveReload? I haven't done so yet but would like to give it a try. Other than that this project will compile Sass, run autoprefixer, and liveReload out of the box.

**Comment by oriSomething** [comment]
about `browse-sync`, personally i use it in some projects and it's great but, the problem with it, that there is no a common port number for php servers. using php command line server is not an options, because we'll need to do the same with mysql and then maybe someone uses mariadb and… a big mess.
livereload is common enough and not depended on a specific port.

**Comment by joshhowenstine** [comment]
I am using MAMP Pro right now which should work fine since it uses a specific port but I see what you mean about the problems that you would experience with other servers and databases.

**Comment by isaacalves** [comment]
The thing is I'm not sure how is the intended use of this theme in terms of workflow. For example, I want to develop a theme for a single project, starting out from html5blank, and I'd like to use gulp tasks for development (watch, browsersync or livereload, sass compiling, wire dependencies from bower), but I need to test the theme against a WordPress installation and a database (local or remote). I'd also like to have a repository for this project (I started one out from this one: https://github.com/markjaquith.... Now how does everything go together? Is it a good idea to have my html5blank-based theme in a separate folder and symlink the src/ folder with a folder inside content/themes of a WordPress installation? How can this be managed for both development and production? I'm looking for a very simple way to set this up. What are some good practices for that setup?

**Comment by oriSomething** [comment]
sorry, but i just don't understand you.
you have on the readme file explantation what todo.
no you don't need a symlink. they can development and production versions can live together

**Comment by isaacalves** [comment]
In the readme file, it says to download the latest version from html5blank.com and uncompress to the WordPress themes folder. However, the 'stable version' that is available for download on that page contains only the content of `src/` of the 'master-version', that is, no bower.json, package.json, gulpfile.js, etc, so how am I suppose to run `bower install` or `npm install` and run gulp tasks, as suggested in the readme file? Or should I clone this repository inside `wp-content/themes/mytheme` folder and the `src` folder would be the theme? That wouldn't work, right? Or should I clone this repo inside the `wp-content/themes` folder and the `src` folder would be the theme folder? Doesn't look to good, right?. It's a very simple question, and I'm probably missing something that's very obvious. Hope I'm being clear now, thanks for your attention.

**Comment by oriSomething** [comment]
i fix some of the readme: 1472df00df2aac59dddaa245df5222eaea0dd58b
i hope now it's clearer. anyway @toddmotto i think it's time to update http://html5blank.com/ so at least it will download the file from the master branch

**Comment by isaacalves** [comment]
thanks!
